name: note_app
description: note app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.0.0
  freezed_annotation: ^2.4.1
  riverpod_annotation: ^2.1.5
  go_router: ^10.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  flutter_riverpod: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.2
  riverpod_generator: ^2.3.2
  custom_lint: ^0.5.3
  riverpod_lint: ^2.1.0
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/profile.png
    - assets/empty_notes.webp
    - assets/empty_favorites.webp
    - assets/app_icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios:
    remove_alpha_ios: true
  image_path: "assets/app_icon.png"
  web:
    generate: true
    image_path: "assets/app_icon.png"